### PR TITLE
don't strip first letter of messages sent to slack

### PR DESCRIPTION
**Pull request by sandsmark**

### CODE REVIEW

**Comment by sandsmark** [comment]
for some reason it seems to happen when the message itself starts with 'h'. but this workaround should work for now at least

**Comment by ltworf** [comment]
How can I reproduce this?

**Comment by sandsmark** [comment]
I just write a single word message to slack, and the first letter is stripped out when I view the channel in the slack web client.

**Comment by ltworf** [comment]
I can't reproduce, could be something your client is doing. Can you use tcpdump to show here what is the string that it sends for a private message?

**Comment by sandsmark** [comment]
it just sends the message as normal, it just doesn't prefix with ':'. 

from looking at the code, it seems like it is explicit if the message to send doesn't contain any spaces. it's apparently to make custom commands work with some ircds.

https://github.com/quassel/quassel/commit/155eda45e862f42a0b9444d615002deda461328d

**Pull request merged**
