### PR TITLE
Sends smaller /names list.

### PR DESCRIPTION
**Pull request by rbarrois**
Some clients might not expect a single line containing all 17k members
of a channel; send them by batches of 50.

Notes:
- The batch size might need some tuning
- I don't have access to a "big" slack instance, so I'd be interested in getting some testing from someone who has that access (maybe @Hack5190 ?)

### CODE REVIEW

**Comment by Hack5190** [comment]
Just let me know.

**Comment by ltworf** [comment]
Does this thing work or not? I can't really test it.

**Comment by Hack5190** [comment]
No observed difference.

**Comment by ltworf** [comment]
Inactive, it seems

**Pull request closed without merging**
