### PR TITLE
Improve mentions

### PR DESCRIPTION
**Pull request by pommi**
See commit messages

### CODE REVIEW

**Comment by knorrie** [comment]
Hi, I just tested this, it works as described.

* "nick: text here" in irssi will result in @nick as seen in slack
* the word are is not turned into a user mention any more (we have a user with this nickname)

Great.

**Comment by knorrie** [comment]
And now I hilighted another github user as result. Hehe, sorry! :-)

**Comment by ltworf** [comment]
I don't see how this improves things…

For example if I write `As I said to username, bla bla` it won't pick it up with this new regexp. Which is not how highlights work in IRC.

**Comment by ltworf** [comment]
Closing since I got no response.

**Pull request closed without merging**
